export const TextAssets = new Map();
TextAssets.set("English-Raw", {
    welcome: "Welcome",
    start_interview: "Start Interview",
    start: "Start",
    show_transcript: "Show Transcript",
    hide_transcript: "Hide Transcript",
    question: "Question",
    your_answer: "Your answer",
    revisit: "Revisit this question",
    show_conclusion: "Show Conclusion",
    home: "Home",
    welcome: "Welcome to the PolicyModels test site!",
    result: "Your results",
    conclusion_page: "Conclusion Page",
    press_conclusions: "Press the \"show conclusion\" button to see the conclusion of your interview",
    download_transcript: "Download Transcript",
    write_feedback: "Write feedback",
    submit_feedback: "submit feedback",
    show_tags: "Show Current Tags (intermediate result)",
    hide_tags: "Hide Current Tags (intermediate result)",
    my_feedback_is: "My Feedback is:",
    my_name_is: "My name is:",
    download_conclusions: "Download Conclusions",
    enter_answer: "Enter your answer here",
    write_comment: "Add personal comment",
    hide_comment: "Hide comment",
    my_comment_is: "my comment is:"
});
TextAssets.set("en-US", {
    welcome: "Welcome",
    start_interview: "Start Interview",
    start: "Start",
    show_transcript: "Show Transcript",
    hide_transcript: "Hide Transcript",
    question: "Question",
    your_answer: "Your answer",
    revisit: "Revisit this question",
    show_conclusion: "Show Conclusion",
    home: "Home",
    welcome: "Welcome to the PolicyModels test site!",
    result: "Your results",
    conclusion_page: "Conclusion Page",
    press_conclusions: "Press the \"show conclusion\" button to see the conclusion of your interview",
    download_transcript: "Download Transcript",
    write_feedback: "Write feedback",
    submit_feedback: "submit feedback",
    show_tags: "Show Current Tags (intermediate result)",
    hide_tags: "Hide Current Tags (intermediate result)",
    my_feedback_is: "My Feedback is:",
    my_name_is: "My name is:",
    download_conclusions: "Download Conclusions",
    enter_answer: "Enter your answer here",
    write_comment: "Add personal comment",
    hide_comment: "Hide comment",
    my_comment_is: "my comment is:"
});
TextAssets.set("he-IL", {
    welcome: "ברוכים הבאים",
    start_interview: "התחל ראיון",
    start: "התחלה",
    show_transcript: "הראה תשובות",
    hide_transcript: "הסתר תשובות",
    question: "שאלה",
    your_answer: "התשובה שלך",
    revisit: "חזור לשאלה זו",
    show_conclusion: "הראה תוצאות",
    home: "חזרה לעמוד הבית",
    welcome: "ברוכים הבאים לאתר הזמני של PolicyModels",
    result: "התוצאות שלך",
    conclusion_page: "עמוד התוצאות",
    press_conclusions: "לחץ על כפתור \"הראה תוצאות\" על מנת לראות את תוצאות הראיון",
    download_transcript: "הורד גיליון תשובות",
    write_feedback: "כתוב משוב",
    submit_feedback: "שלח משוב",
    show_tags: "הראה תוצאות ביניים",
    hide_tags: "הסתר תוצאות ביניים",
    my_feedback_is: "המשוב שלי הוא:",
    my_name_is: "השם שלי הוא:",
    download_conclusions: "הורד תוצאות",
    enter_answer: "הכנס את התשובה שלך כאן",
    write_comment: "הוסף הערה אישית",
    hide_comment: "הסתר הערה",
    my_comment_is: "ההערה שלי היא:"
});

